#spring redis相关配置  org.springframework.boot.autoconfigure.data.redis.RedisProperties
spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 123456
    timeout:
      seconds: 5
        
